name: Build and Deploy Blazor WebAssembly

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v3

      - name: Configurar .NET 8
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "8.0.x"

      - name: Restaurar dependencias
        run: dotnet restore TorosClient/TorosClient.csproj

      - name: Publicar la aplicación Blazor WebAssembly
        run: dotnet publish TorosClient/TorosClient.csproj -c Release -o build

      - name: Configurar el Agente SSH
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Agregar host a known_hosts
        run: |
          ssh-keyscan -H ${{ secrets.SERVER_HOST }} >> ~/.ssh/known_hosts

      - name: Desplegar al servidor vía rsync
        run: |
          rsync -avz --delete build/wwwroot/ ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }}:${{ secrets.DEPLOY_PATH }}

      - name: Reiniciar Nginx
        run: ssh ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} 'sudo systemctl restart nginx'
